/*
 * File: app/model/persona/Cargo.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.model.persona.Cargo', {
    extend: 'Ext.data.Model',
    alias: 'model.cargo',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            name: 'nombre'
        },
        {
            type: 'string',
            name: 'nivel_educacional'
        },
        {
            type: 'string',
            name: 'nivel_educacional_id'
        },
        {
            type: 'string',
            name: 'categoria'
        },
        {
            type: 'string',
            name: 'categoria_id'
        },
        {
            type: 'string',
            name: 'calificador'
        },
        {
            type: 'string',
            name: 'calificador_id'
        },
        {
            name: 'periodo_prueba'
        },
        {
            type: 'boolean',
            name: 'funcionario'
        },
        {
            name: 'grupo_escala'
        },
        {
            name: 'grupo_escala_id'
        }
    ]
});