/*
 * File: app/model/persona/MovimientoEmpleado.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.model.persona.MovimientoEmpleado', {
    extend: 'Ext.data.Model',
    alias: 'model.movimientoempleado',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number',
        'Ext.data.field.Boolean',
        'Ext.data.proxy.Rest',
        'Ext.data.writer.Json',
        'Ext.data.reader.Json'
    ],

    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            type: 'string',
            name: 'altaempleado'
        },
        {
            type: 'string',
            name: 'altaempleado_id'
        },
        {
            type: 'string',
            name: 'numero'
        },
        {
            type: 'string',
            name: 'expediente'
        },
        {
            type: 'date',
            name: 'fecha_efectivo',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'causamovimiento'
        },
        {
            type: 'string',
            name: 'causamovimiento_id'
        },
        {
            type: 'string',
            name: 'tipocontrato'
        },
        {
            type: 'string',
            name: 'tipocontrato_actual'
        },
        {
            type: 'string',
            name: 'tipocontrato_id'
        },
        {
            type: 'string',
            name: 'tipocontrato_actual_id'
        },
        {
            type: 'string',
            name: 'regimensalarial_actual_id'
        },
        {
            type: 'string',
            name: 'regimensalarial_id'
        },
        {
            type: 'string',
            name: 'regimensalarial'
        },
        {
            type: 'string',
            name: 'regimensalarial_actual'
        },
        {
            type: 'string',
            name: 'area_id'
        },
        {
            type: 'string',
            name: 'area_actual_id'
        },
        {
            type: 'string',
            name: 'area'
        },
        {
            type: 'string',
            name: 'area_actual'
        },
        {
            type: 'string',
            name: 'cargo_id'
        },
        {
            type: 'string',
            name: 'cargo_actual_id'
        },
        {
            type: 'string',
            name: 'cargo'
        },
        {
            type: 'string',
            name: 'cargo_actual'
        },
        {
            type: 'string',
            name: 'plaza_actual_id'
        },
        {
            type: 'string',
            name: 'plaza_id'
        },
        {
            type: 'string',
            name: 'plaza'
        },
        {
            type: 'string',
            name: 'plaza_actual'
        },
        {
            type: 'string',
            name: 'tipocalendario_id'
        },
        {
            type: 'string',
            name: 'tipocalendario_actual_id'
        },
        {
            type: 'string',
            name: 'tipocalendario'
        },
        {
            type: 'string',
            name: 'tipocalendario_actual'
        },
        {
            type: 'string',
            name: 'tipopago_actual_id'
        },
        {
            type: 'string',
            name: 'tipopago_id'
        },
        {
            type: 'string',
            name: 'tipopago'
        },
        {
            type: 'string',
            name: 'tipopago_actual'
        },
        {
            type: 'float',
            name: 'basico'
        },
        {
            type: 'float',
            name: 'basico_actual'
        },
        {
            type: 'float',
            name: 'estimulo'
        },
        {
            type: 'float',
            name: 'estimulo_actual'
        },
        {
            type: 'float',
            name: 'plus'
        },
        {
            type: 'float',
            name: 'plus_actual'
        },
        {
            type: 'float',
            name: 'antiguedad'
        },
        {
            type: 'float',
            name: 'antiguedad_actual'
        },
        {
            type: 'string',
            name: 'antiguedad_id'
        },
        {
            type: 'string',
            name: 'antiguedad_actual_id'
        },
        {
            type: 'string',
            name: 'centrocosto_actual_id'
        },
        {
            type: 'string',
            name: 'centrocosto_actual'
        },
        {
            type: 'string',
            name: 'centrocosto'
        },
        {
            type: 'string',
            name: 'centrocosto_id'
        },
        {
            type: 'float',
            name: 'salario_cargo'
        },
        {
            type: 'float',
            name: 'salario_cargo_actual'
        },
        {
            type: 'float',
            name: 'otros'
        },
        {
            type: 'float',
            name: 'otros_actual'
        },
        {
            type: 'float',
            name: 'porciento'
        },
        {
            type: 'float',
            name: 'porciento_actual'
        },
        {
            type: 'float',
            name: 'dias'
        },
        {
            type: 'float',
            name: 'dias_actual'
        },
        {
            type: 'float',
            name: 'importe'
        },
        {
            type: 'float',
            name: 'importe_actual'
        },
        {
            type: 'float',
            name: 'divisa'
        },
        {
            type: 'float',
            name: 'divisa_actual'
        },
        {
            type: 'float',
            name: 'tarifa_divisa'
        },
        {
            type: 'float',
            name: 'tarifa_divisa_actual'
        },
        {
            type: 'float',
            name: 'coeficiente_tarifa_divisa'
        },
        {
            type: 'float',
            name: 'coeficiente_tarifa_divisa_actual'
        },
        {
            type: 'float',
            name: 'idoneidad_fijo'
        },
        {
            type: 'float',
            name: 'idoneidad_fijo_actual'
        },
        {
            type: 'float',
            name: 'idoneidad_movil'
        },
        {
            type: 'float',
            name: 'idoneidad_movil_actual'
        },
        {
            type: 'float',
            name: 'porciento_retribuicion_complementaria'
        },
        {
            type: 'float',
            name: 'porciento_retribuicion_complementaria_actual'
        },
        {
            type: 'float',
            name: 'pago_divisa_valor'
        },
        {
            type: 'float',
            name: 'pago_divisa_valor_actual'
        },
        {
            type: 'float',
            name: 'pago_divisa_porciento'
        },
        {
            type: 'float',
            name: 'pago_divisa_porciento_actual'
        },
        {
            type: 'float',
            name: 'estimulacion_valor'
        },
        {
            type: 'float',
            name: 'estimulacion_valor_actual'
        },
        {
            type: 'float',
            name: 'estimulacion_porciento'
        },
        {
            type: 'float',
            name: 'estimulacion_porciento_actual'
        },
        {
            type: 'int',
            name: 'dias_laborables'
        },
        {
            type: 'int',
            name: 'dias_laborables_actual'
        },
        {
            type: 'boolean',
            name: 'descontar_sabados'
        },
        {
            type: 'boolean',
            name: 'descontar_sabados_actual'
        },
        {
            type: 'boolean',
            name: 'acumula_vacaciones'
        },
        {
            type: 'boolean',
            name: 'acumula_vacaciones_actual'
        }
    ],

    proxy: {
        type: 'rest',
        api: {
            add: {
                url: 'index.php/api/restserver/rests',
                method: 'POST'
            },
            show: {
                url: 'index.php/api/restserver/rests/',
                method: 'GET'
            },
            save: {
                url: 'index.php/api/restserver/rests/id/{id}',
                method: 'PUT'
            },
            remove: {
                url: 'index.php/api/restserver/rests/id/{id}',
                method: 'DELETE'
            }
        },
        extraParams: {
            model: 'movimientoempleado',
            esquema: 'persona'
        },
        url: 'index.php/api/restserver/rests/',
        writer: {
            type: 'json',
            writeAllFields: true,
            encode: true,
            rootProperty: 'data'
        },
        reader: {
            type: 'json',
            rootProperty: 'data'
        }
    }
});