/*
 * File: app/store/persona/PersonaEntidad.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.store.persona.PersonaEntidad', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'cerodatax.model.persona.PersonaEntidad',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'persona.PersonaEntidad',
            autoLoad: false,
            autoSync: true,
            model: 'cerodatax.model.persona.PersonaEntidad',
            folderSort: true,
            proxy: {
                type: 'rest',
                extraParams: {
                    model: 'entidad',
                    esquema: 'estructura',
                    parent_id: '',
                    esquema_asociado: 'persona',
                    asociados: 'persona',
                    id_asociado: '',
                    detalles: ''
                },
                url: 'index.php/api/restserver/rests/',
                format: '',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    encode: true,
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});