/*
 * File: app/view/persona/Cargo.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.persona.Cargo', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.personacargo',

    requires: [
        'cerodatax.view.persona.CargoViewModel',
        'cerodatax.view.persona.CargoViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Boolean',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.selection.RowModel',
        'Ext.grid.filters.Filters',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.form.field.Checkbox'
    ],

    controller: 'personacargo',
    viewModel: {
        type: 'personacargo'
    },
    controller: 'nomencladorcrud',
    height: 528,
    shrinkWrap: 0,
    width: 837,
    layout: 'border',
    collapsed: false,

    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            region: 'center',
            split: true,
            reference: 'list',
            itemId: 'gridPanel',
            resizable: false,
            title: '',
            forceFit: true,
            store: 'persona.Cargo',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombre',
                    text: 'Nombre11'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nivel_educacional',
                    text: 'Nivel Educacional'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'categoria_cargo',
                    text: 'Categoria'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'calificador',
                    text: 'Calificador'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'periodo_prueba',
                    text: 'Periodo de Prueba'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'funcionario',
                    text: 'Funcionario'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'grupoescala',
                    text: 'Grupo Escala'
                }
            ],
            listeners: {
                select: 'select'
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'persona.Cargo'
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnAdd',
                            text: 'Adicionar',
                            listeners: {
                                click: 'add'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnEdit',
                            text: 'Editar',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'edit'
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'btnRemove',
                            text: 'Eliminar',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'remove'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnRefresh',
                            text: 'Actualizar',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'refresh'
                            }
                        }
                    ],
                    listeners: {
                        afterrender: 'onToolbarAfterRender'
                    }
                }
            ],
            selModel: {
                selType: 'rowmodel',
                mode: 'MULTI'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'south',
            split: true,
            reference: 'display',
            height: 150,
            layout: 'card',
            bodyBorder: true,
            items: [
                {
                    xtype: 'panel',
                    reference: 'selectMessage',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            html: '<h1>Seleccione el Cargo</h1>'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'details',
                    padding: '10 10 10 10',
                    bodyPadding: 10,
                    bodyStyle: 'padding:10px 10px 10px 10px',
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Nombre',
                            bind: {
                                value: '{record.nombre}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Nivel Educacional',
                            bind: {
                                value: '{record.nivel_educacional}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Categoria',
                            bind: {
                                value: '{record.categoria}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Calificador',
                            bind: {
                                value: '{record.calificador}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Periodo de Prueba',
                            bind: {
                                value: '{record.periodo_prueba}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Funcionario',
                            bind: {
                                value: '{record.funcionario}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Grupo Escala',
                            bind: {
                                value: '{record.grupo_escala}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'form',
                    reference: 'form',
                    alignTarget: 'top',
                    itemId: 'cargoForm',
                    bodyPadding: 10,
                    title: 'Editar Cargo',
                    fieldDefaults: {
                        padding: '0 10 0 10',
                        maxLength: 30,
                        enforceMaxLength: true
                    },
                    layout: {
                        type: 'table',
                        columns: 3
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            afterLabelTextTpl: [
                                '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                            ],
                            fieldLabel: 'Nombre',
                            name: 'nombre',
                            allowBlank: false,
                            maxLength: 100
                        },
                        {
                            xtype: 'combobox',
                            afterLabelTextTpl: [
                                '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                            ],
                            fieldLabel: 'Nivel Educacional',
                            name: 'nivel_educacional_id',
                            allowBlank: false,
                            emptyText: 'Seleccione',
                            displayField: 'nombre',
                            queryMode: 'local',
                            store: 'nomenclador.NivelEducacional',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            afterLabelTextTpl: [
                                '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                            ],
                            fieldLabel: 'Categoria',
                            name: 'categoria_cargo_id',
                            allowBlank: false,
                            emptyText: 'Seleccione',
                            displayField: 'nombre',
                            queryMode: 'local',
                            store: 'nomenclador.CategoriaCargo',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            afterLabelTextTpl: [
                                '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                            ],
                            fieldLabel: 'Grupo Escala',
                            name: 'grupoescala_id',
                            allowBlank: false,
                            displayField: 'nombre',
                            queryMode: 'local',
                            store: 'nomenclador.GrupoEscala',
                            valueField: 'id',
                            listConfig: {
                                xtype: 'boundlist',
                                itemSelector: 'div',
                                itemTpl: [
                                    ' {nombre} ({salario})'
                                ]
                            }
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Calificador',
                            name: 'calificador_id',
                            emptyText: 'Seleccione',
                            displayField: 'nombre',
                            queryMode: 'local',
                            store: 'nomenclador.Calificador',
                            valueField: 'id'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Periodo de Prueba',
                            name: 'periodo_prueba',
                            maxLength: 3
                        },
                        {
                            xtype: 'checkboxfield',
                            fieldLabel: 'Funcionario',
                            name: 'funcionario'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'bottom',
                            padding: 10,
                            layout: 'form',
                            items: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    itemId: 'saveButton',
                                    margin: 5,
                                    text: 'Guardar',
                                    listeners: {
                                        click: 'save'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancelButton',
                                    margin: 5,
                                    text: 'Cancelar',
                                    listeners: {
                                        click: 'cancelEdit'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    initConfig: function(instanceConfig) {
        var me = this,
            config = {};
        me.processPersonaCargo(config);
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processPersonaCargo: function(config) {
        var control = Ext.create('cerodatax.view.nomenclador.CrudViewController'),
            result = [],
            columns=[],
            resultgrid = [];
        result = control.searchComponent('form', this, result);
        resultgrid = control.searchComponent('gridpanel', this, resultgrid);

        if(result.length > 0)
        {var formPanel = result[0],


            columns = control.searchLabel(formPanel.items,columns,true);
        control.formatForm(formPanel);
         if(resultgrid.length > 0)
             control.configGridPanel(resultgrid[0],columns);
         control.createDetails(this,columns);
        }


        return config;
    }

});