/*
 * File: app/view/comercial/FormContacto.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.comercial.FormContacto', {
    extend: 'Ext.window.Window',
    alias: 'widget.ComercialFormulario',

    requires: [
        'cerodatax.view.comercial.FormContactoViewModel'
    ],

    viewModel: {
        type: 'comercialformcontacto'
    },
    height: 250,
    width: 400

});