/*
 * File: app/view/estructura/AreaPlazaForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.estructura.AreaPlazaForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.areaplazaForm',

    requires: [
        'cerodatax.view.seguridad.UsuarioRolFormViewModel1',
        'cerodatax.view.seguridad.UsuarioRolFormViewController1',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.view.MultiSelector',
        'Ext.view.MultiSelectorSearch',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.Filters',
        'Ext.button.Button'
    ],

    controller: 'estructuraareaplazaform',
    viewModel: {
        type: 'estructuraareaplazaform'
    },
    controller: 'nomencladorcrud',
    resizable: false,
    bodyPadding: 10,
    title: 'Plazas',
    modal: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            height: 480,
            width: 400,
            layout: 'auto',
            bodyPadding: 10,
            fieldDefaults: {
                padding: '0 10 0 0',
                enforceMaxLength: true
            },
            items: [
                {
                    xtype: 'displayfield',
                    width: 380,
                    fieldLabel: 'Área',
                    labelWidth: 40,
                    name: 'nombre'
                },
                {
                    xtype: 'multiselector',
                    height: 400,
                    scrollable: 'true',
                    title: 'Plazas',
                    emptyText: 'No existen elementos que mostrar',
                    reserveScrollbar: true,
                    store: 'estructura.AreaPlaza',
                    addToolText: 'Busca un elemento para adicionar',
                    removeRowTip: 'Elimina este elemento',
                    search: {
                        xtype: 'multiselector-search',
                        searchText: 'Buscar...',
                        store: 'estructura.Plaza',
                        field: 'cargo'
                    },
                    viewConfig: {
                        width: 360,
                        deferEmptyText: false
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'cargo',
                            text: 'Cargo',
                            flex: 2,
                            filter: {
                                type: 'string',
                                emptyText: 'Ingrese el texto del filtro...'
                            }
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'gridfilters',
                            menuFilterText: 'Buscar'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    padding: 10,
                    layout: 'form',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Guardar',
                            listeners: {
                                click: 'saveTreeWindows'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancelar',
                            listeners: {
                                click: 'cancelEdit'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});