/*
 * File: app/view/rh/ClaveAusenciaForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.rh.ClaveAusenciaForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.claveausenciaForm',

    requires: [
        'cerodatax.view.nomenclador.AlmacenFormViewModel2',
        'cerodatax.view.nomenclador.AlmacenFormViewController2',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Spinner',
        'Ext.button.Button'
    ],

    controller: 'rhclaveausenciaform',
    viewModel: {
        type: 'rhclaveausenciaform'
    },
    controller: 'nomencladorcrud',
    height: 520,
    resizable: false,
    width: 435,
    bodyPadding: 10,
    title: 'Clave Ausencia',
    modal: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    me.processForm({
                        xtype: 'form',
                        reference: 'form',
                        height: 491,
                        width: 420,
                        bodyPadding: 10,
                        fieldDefaults: {
                            maxLength: 100,
                            enforceMaxLength: true
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                alignTarget: 'top',
                                height: 215,
                                width: 402,
                                title: 'Información',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Código',
                                        name: 'codigo',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Nombre',
                                        name: 'nombre',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'combobox',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Tipo Causa de Ausencia',
                                        name: 'tipocausaausencia_id',
                                        allowBlank: false,
                                        emptyText: 'Seleccione',
                                        displayField: 'nombre',
                                        queryMode: 'local',
                                        store: 'nomenclador.TipoCausaAusencia',
                                        valueField: 'id'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        fieldLabel: 'Deducible',
                                        name: 'deducible',
                                        checked: true
                                    },
                                    {
                                        xtype: 'combobox',
                                        fieldLabel: 'A Pagar Por',
                                        name: 'apagarpor_id',
                                        emptyText: 'Seleccione',
                                        displayField: 'nombre',
                                        queryMode: 'local',
                                        store: 'nomenclador.APagarPor',
                                        valueField: 'id'
                                    },
                                    {
                                        xtype: 'spinnerfield',
                                        minWidth: 0,
                                        width: 180,
                                        fieldLabel: 'Porciento',
                                        name: 'porciento'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                height: 167,
                                width: 401,
                                layout: 'column',
                                title: 'Generales',
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        width: 120,
                                        fieldLabel: 'No Acumala Vacaciones de Días e Importe',
                                        name: 'no_acumala_vacaciones_dias_importe',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        margin: '0 0 0 10',
                                        width: 120,
                                        fieldLabel: 'Afecta Subsidio',
                                        name: 'afecta_subsidio',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        margin: '0 0 0 10',
                                        width: 100,
                                        fieldLabel: 'Afecta Tarjeta Día y Tarjeta Importe',
                                        name: 'afecta_tarjeta_dias_importe',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        width: 120,
                                        fieldLabel: 'Afecta Evaluación',
                                        name: 'afecta_evaluacion',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        margin: '0 0 0 10',
                                        width: 120,
                                        fieldLabel: 'Afecta Estímulo',
                                        name: 'afecta_estimulo',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        margin: '0 0 0 10',
                                        width: 100,
                                        fieldLabel: 'Afecta Reporte de Ausencias',
                                        name: 'afecta_reporte_ausencia',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        width: 120,
                                        fieldLabel: 'Afecta Prom. Total de Trab.',
                                        name: 'afecta_promedio_total_trab',
                                        checked: true
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        margin: '0 0 0 10',
                                        width: 120,
                                        fieldLabel: 'Clasificación Fdo. De Tiempo',
                                        name: 'fondo_tiempo',
                                        checked: true
                                    }
                                ]
                            }
                        ],
                        dockedItems: [
                            {
                                xtype: 'container',
                                dock: 'bottom',
                                height: 84,
                                padding: 10,
                                layout: 'form',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'saveButton',
                                        margin: 5,
                                        text: 'Guardar',
                                        listeners: {
                                            click: 'saveTreeWindows'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        text: 'Cancelar',
                                        listeners: {
                                            click: 'cancelEdit'
                                        }
                                    }
                                ]
                            }
                        ]
                    })
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processForm: function(config) {
        return config;
    }

});