/*
 * File: app/view/nomenclador/AlmacenForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.nomenclador.AlmacenForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.almacenForm',

    requires: [
        'cerodatax.view.nomenclador.AlmacenFormViewModel',
        'cerodatax.view.nomenclador.AlmacenFormViewController',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.XTemplate',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date'
    ],

    controller: 'nomencladoralmacenform',
    viewModel: {
        type: 'nomencladoralmacenform'
    },
    controller: 'nomencladorcrud',
    resizable: false,
    bodyPadding: 10,
    title: 'Almacen',
    modal: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    me.processForm({
                        xtype: 'form',
                        reference: 'form',
                        alignTarget: 'top',
                        width: 656,
                        bodyPadding: 10,
                        fieldDefaults: {
                            padding: '0 10 0 0',
                            maxLength: 100,
                            enforceMaxLength: true
                        },
                        layout: {
                            type: 'table',
                            columns: 2
                        },
                        dockedItems: [
                            {
                                xtype: 'container',
                                dock: 'bottom',
                                padding: 10,
                                layout: 'form',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'saveButton',
                                        margin: 5,
                                        text: 'Guardar',
                                        listeners: {
                                            click: 'saveTreeWindows'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        text: 'Cancelar',
                                        listeners: {
                                            click: 'cancelEdit'
                                        }
                                    }
                                ]
                            }
                        ],
                        items: [
                            {
                                xtype: 'tabpanel',
                                width: 643,
                                activeTab: 0,
                                items: [
                                    {
                                        xtype: 'panel',
                                        height: 241,
                                        width: 548,
                                        layout: 'table',
                                        title: 'Datos Generales',
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                alignTarget: 'top',
                                                height: 197,
                                                margin: '10 0 0 0',
                                                width: 300,
                                                layout: 'column',
                                                title: 'Información',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Código',
                                                        name: 'codigo',
                                                        allowBlank: false,
                                                        maxLength: 100
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Nombre',
                                                        name: 'nombre',
                                                        allowBlank: false,
                                                        maxLength: 100
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Letra',
                                                        name: 'letra',
                                                        allowBlank: false,
                                                        maxLength: 5
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Teléfono',
                                                        name: 'telefono',
                                                        inputType: 'tel',
                                                        maskRe: /\d/,
                                                        maxLength: 30
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Dirección',
                                                        name: 'direccion',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'radiogroup',
                                                        width: 548,
                                                        fieldLabel: 'Documento para Ordenar',
                                                        layout: {
                                                            type: 'vbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'radiofield',
                                                                flex: 1,
                                                                name: 'documento_ordenar',
                                                                value: 1,
                                                                boxLabel: 'Orden de Compra',
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'radiofield',
                                                                name: 'documento_ordenar',
                                                                value: 2,
                                                                boxLabel: 'Solicitud de Entrega'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                margin: '10 0 0 10',
                                                width: 321,
                                                title: 'Generales',
                                                items: [
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Centro de Costo',
                                                        labelWidth: 120,
                                                        name: 'centrocosto_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.CentroCosto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Tipo de Entrada',
                                                        labelWidth: 120,
                                                        name: 'tipoentrada_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.TipoEntrada',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Criterio de Salida',
                                                        labelWidth: 120,
                                                        name: 'criteriosalida_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.CriterioSalida',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Especificación de Insumo',
                                                        labelWidth: 120,
                                                        name: 'especificacioninsumo_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.EspecificacionInsumo',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Clasificación Contable',
                                                        labelWidth: 120,
                                                        name: 'clasificacioncontable_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.ClasificacionContable',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'datefield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Fecha Alta',
                                                        labelWidth: 120,
                                                        name: 'fecha_alta',
                                                        allowBlank: false,
                                                        altFormats: '',
                                                        format: 'Y-m-d',
                                                        submitFormat: 'Y-m-d'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        margin: '10 0 0 0',
                                        width: 150,
                                        title: 'Punto de Venta',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                fieldLabel: 'Punto de Venta Activo',
                                                labelWidth: 140,
                                                name: 'punto_venta'
                                            },
                                            {
                                                xtype: 'fieldset',
                                                title: 'Generar Factura',
                                                items: [
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Cliente',
                                                        name: 'cliente_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'contacto',
                                                        queryMode: 'local',
                                                        store: 'crm.Cliente',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Vendedor',
                                                        name: 'vendedor_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'persona.Persona',
                                                        valueField: 'id'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    })
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processForm: function(config) {
        return config;
    }

});