/*
 * File: app/view/nomenclador/BancoForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.nomenclador.BancoForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.bancoForm',

    requires: [
        'cerodatax.view.nomenclador.BancoFormViewModel',
        'cerodatax.view.nomenclador.BancoFormViewController',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.Img',
        'Ext.form.field.File',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox'
    ],

    controller: 'nomencladorbancoform',
    viewModel: {
        type: 'nomencladorbancoform'
    },
    controller: 'nomencladorcrud',
    resizable: false,
    bodyPadding: 10,
    title: 'Banco',
    modal: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        reference: 'form',
                        alignTarget: 'top',
                        height: 500,
                        width: 460,
                        layout: 'auto',
                        bodyPadding: 10,
                        fieldDefaults: {
                            padding: '0 10 0 0',
                            maxLength: 100,
                            enforceMaxLength: true
                        },
                        dockedItems: [
                            {
                                xtype: 'container',
                                dock: 'bottom',
                                padding: 10,
                                layout: 'form',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'saveButton',
                                        margin: 5,
                                        text: 'Guardar',
                                        listeners: {
                                            click: 'saveTreeWindows'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        text: 'Cancelar',
                                        listeners: {
                                            click: 'cancelEdit'
                                        }
                                    }
                                ]
                            }
                        ],
                        items: [
                            {
                                xtype: 'tabpanel',
                                width: 440,
                                activeTab: 0,
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: 'Datos Generales',
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                alignTarget: 'top',
                                                height: 170,
                                                margin: '10 0 0 0',
                                                width: 440,
                                                layout: 'column',
                                                title: 'Información',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        height: 130,
                                                        margin: '10 10 0 0',
                                                        width: 110,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                alwaysOnTop: true,
                                                                shim: false,
                                                                frame: false,
                                                                height: 110,
                                                                hidden: true,
                                                                itemId: 'foto',
                                                                style: 'font-size: 36px; lineHeight: 36px',
                                                                width: 100,
                                                                alt: 'Cargando Foto...',
                                                                imgCls: ''
                                                            },
                                                            {
                                                                xtype: 'image',
                                                                alwaysOnTop: true,
                                                                shim: false,
                                                                frame: true,
                                                                height: 80,
                                                                itemId: 'foto1',
                                                                style: 'font-size: 80px; margin: 10px;line-height: 120px;',
                                                                width: 80,
                                                                alt: 'Cargando Foto...',
                                                                glyph: 'xf19c@FontAwesome'
                                                            }
                                                        ]
                                                    },
                                                    me.processLogotipo({
                                                        xtype: 'filefield',
                                                        fieldLabel: 'Logotipo',
                                                        labelPad: -20,
                                                        name: 'logotipo',
                                                        emptyText: 'Seleccione',
                                                        buttonText: 'Examinar...',
                                                        listeners: {
                                                            change: 'onFilefieldChange'
                                                        }
                                                    }),
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Nombre',
                                                        name: 'nombre',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Tipo de Banco',
                                                        name: 'tipo_banco_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.TipoBanco',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Presidente',
                                                        name: 'presidente',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Swift',
                                                        name: 'swift_code'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                margin: '10 0 0 0',
                                                width: 440,
                                                title: 'Contacto',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Dirección',
                                                        name: 'direccion',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Correo',
                                                        name: 'correo',
                                                        inputType: 'email',
                                                        vtype: 'email'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Teléfono',
                                                        name: 'telefono',
                                                        inputType: 'tel',
                                                        maskRe: /\d/,
                                                        maxLength: 30
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Fax',
                                                        name: 'fax',
                                                        inputType: 'tel',
                                                        maskRe: /\d/,
                                                        maxLength: 30
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Telex',
                                                        name: 'telex',
                                                        inputType: 'tel',
                                                        maskRe: /\d/,
                                                        maxLength: 30
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Web',
                                                        name: 'web',
                                                        inputType: 'tel',
                                                        maskRe: /\d/
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        margin: '10 0 0 0',
                                        width: 150,
                                        title: 'Otros Datos',
                                        items: [
                                            {
                                                xtype: 'combobox',
                                                fieldLabel: 'País',
                                                name: 'pais_id',
                                                emptyText: 'Seleccione',
                                                displayField: 'nombre',
                                                queryMode: 'local',
                                                queryParam: 'provincia_id:false,municipio_id:true',
                                                store: 'nomenclador.Pais',
                                                valueField: 'id',
                                                listeners: {
                                                    select: 'onComboboxSelect1'
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                disabled: true,
                                                fieldLabel: 'Provincia',
                                                name: 'provincia_id',
                                                emptyText: 'Seleccione',
                                                displayField: 'nombre',
                                                queryMode: 'local',
                                                queryParam: 'municipio_id:false',
                                                store: 'nomenclador.Provincia',
                                                valueField: 'id',
                                                listeners: {
                                                    select: 'onComboboxSelect'
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                disabled: true,
                                                fieldLabel: 'Municipio',
                                                name: 'municipio_id',
                                                emptyText: 'Seleccione',
                                                displayField: 'nombre',
                                                queryMode: 'local',
                                                store: 'nomenclador.Municipio',
                                                valueField: 'id'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        hidden: true,
                                        title: 'Cuentas Bancarias'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processLogotipo: function(config) {
        config.icono = 'institution';
        return config;
    }

});