/*
 * File: app/view/nomenclador/CRUD.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.nomenclador.CRUD', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.crud',

    requires: [
        'cerodatax.view.nomenclador.CrudViewModel',
        'cerodatax.view.nomenclador.CrudViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.selection.RowModel',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.Text'
    ],

    controller: 'nomencladorcrud',
    viewModel: {
        type: 'nomencladorcrud'
    },
    shrinkWrap: 0,
    layout: 'border',
    collapsed: false,

    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            region: 'center',
            split: true,
            reference: 'list',
            itemId: 'gridPanelNivel',
            resizable: false,
            title: '',
            forceFit: true,
            store: 'nomenclador.NivelEducacional',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nombre',
                    text: 'Nombre'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'nomenclador.NivelEducacional'
                }
            ],
            selModel: {
                selType: 'rowmodel',
                mode: 'MULTI'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'east',
            split: true,
            reference: 'display',
            width: 150,
            layout: 'card',
            bodyBorder: true,
            items: [
                {
                    xtype: 'panel',
                    reference: 'selectMessage',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            html: '<h1>Seleccione el Nivel Educacional</h1>'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'details',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Nombre',
                            bind: {
                                value: '{record.nombre}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'form',
                    reference: 'form',
                    bodyPadding: 10,
                    title: 'Editar Nivel Educacional',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Nombre',
                            name: 'nombre',
                            allowBlank: false
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'bottom',
                            padding: 10,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    formBind: true,
                                    itemId: 'saveButton',
                                    margin: 5,
                                    text: 'Guardar'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    itemId: 'cancelButton',
                                    margin: 5,
                                    text: 'Cancelar'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnAdd',
                    text: 'Adicionar'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnEdit',
                    glyph: 47,
                    text: 'Editar',
                    bind: {
                        hidden: '{!record}'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnRemove',
                    glyph: 88,
                    text: 'Eliminar',
                    bind: {
                        hidden: '{!record}'
                    }
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnRefresh',
                    text: 'Actualizar',
                    bind: {
                        hidden: '{!record}'
                    }
                }
            ]
        }
    ]

});