/*
 * File: app/controller/Seguridad.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.controller.Seguridad', {
    extend: 'Ext.app.Controller',

    control: {
        "#buttonAutenticacion": {
            click: 'onButtonAutenticacionClick'
        }
    },

    onButtonAutenticacionClick: function(button, e, eOpts) {
        var view = this.getView();
        form = button.up('form');
        formWindow = button.up('window');


        if(form.isValid())
        {
            values = form.getValues();
            // Success
            var successCallback = function(resp, ops) {
                //debugger;
                // Hide login panel
                view.hide();
                // Close window
                formWindow.destroy();

                // Show logout panel
                var viewportEscritorio = Ext.create('cerodatax.view.Escritorio',{

                });
                viewportEscritorio.show();

            };

            // Failure
            var failureCallback = function(resp, ops) {

                // Show login failure error
                Ext.Msg.alert('Login Failure', resp);

            };


            // TODO: Login using server-side authentication service
            Ext.Ajax.request({
                url: "./seguridad/authenticate_user",
                params: values,
                success: successCallback,
                failure: failureCallback
            });
        }



    }

});
