/*
 * File: app/model/nomenclador/CentroCosto.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.model.nomenclador.CentroCosto', {
    extend: 'Ext.data.Model',
    alias: 'model.centrocosto',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            type: 'string',
            name: 'codigo'
        },
        {
            type: 'string',
            name: 'nombre'
        },
        {
            type: 'boolean',
            name: 'activo'
        },
        {
            type: 'string',
            name: 'descripcion'
        },
        {
            type: 'string',
            name: 'grupo_centrocosto'
        },
        {
            type: 'string',
            name: 'grupo_centrocosto_id'
        },
        {
            type: 'string',
            name: 'agrupacion_centrocosto'
        },
        {
            type: 'string',
            name: 'agrupacion_centrocosto_id'
        }
    ]
});