/*
 * File: app/view/crm/ProductosServiciosForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.crm.ProductosServiciosForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.productosserviciosForm',

    requires: [
        'cerodatax.view.crm.ProductosServiciosFormViewModel',
        'cerodatax.view.crm.ProductosServiciosFormViewController',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.Img',
        'Ext.form.field.File',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.grid.column.Widget',
        'Ext.grid.column.Check',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'crmproductosserviciosform',
    viewModel: {
        type: 'crmproductosserviciosform'
    },
    controller: 'nomencladorcrud',
    resizable: false,
    width: 795,
    bodyPadding: 10,
    title: 'Productos y Servicios',
    modal: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        reference: 'form',
                        alignTarget: 'top',
                        layout: 'auto',
                        bodyPadding: 10,
                        fieldDefaults: {
                            padding: '0 10 0 0',
                            maxLength: 50,
                            enforceMaxLength: true
                        },
                        items: [
                            {
                                xtype: 'tabpanel',
                                width: 755,
                                activeTab: 0,
                                items: [
                                    {
                                        xtype: 'panel',
                                        height: 320,
                                        width: 880,
                                        layout: 'column',
                                        title: 'Datos del Producto y Servivio',
                                        items: [
                                            {
                                                xtype: 'fieldset',
                                                alignTarget: 'top',
                                                height: 310,
                                                margin: '10 0 0 0',
                                                width: 435,
                                                layout: 'column',
                                                title: 'Información',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        height: 130,
                                                        margin: '10 10 0 0',
                                                        width: 110,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                alwaysOnTop: true,
                                                                shim: false,
                                                                frame: false,
                                                                height: 110,
                                                                hidden: true,
                                                                itemId: 'foto',
                                                                style: 'font-size: 36px; lineHeight: 36px',
                                                                width: 100,
                                                                alt: 'Cargando Foto...'
                                                            },
                                                            {
                                                                xtype: 'image',
                                                                alwaysOnTop: true,
                                                                shim: false,
                                                                frame: true,
                                                                height: 110,
                                                                itemId: 'foto1',
                                                                style: 'font-size: 110px; margin: 10px;line-height: 120px;',
                                                                width: 100,
                                                                alt: 'Cargando Foto...',
                                                                glyph: 'xf007@FontAwesome'
                                                            }
                                                        ]
                                                    },
                                                    me.processFoto({
                                                        xtype: 'filefield',
                                                        margin: '10 0 0 0',
                                                        fieldLabel: 'Foto',
                                                        name: 'foto',
                                                        invalidText: 'El valor del elemento es invalido',
                                                        emptyText: 'Seleccione',
                                                        buttonText: 'Examinar...',
                                                        listeners: {
                                                            change: 'onFilefieldChange'
                                                        }
                                                    }),
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Código',
                                                        name: 'codigo',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        fieldLabel: 'Código de Barra',
                                                        name: 'codigo_barra'
                                                    },
                                                    {
                                                        xtype: 'textfield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Nombre(s)',
                                                        name: 'nombre',
                                                        allowBlank: false
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'UM Almacen',
                                                        name: 'um_almacen_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'descripcion',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.UnidadMedida',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'UM Venta',
                                                        name: 'um_venta_id',
                                                        allowBlank: false,
                                                        emptyText: 'Seleccione',
                                                        displayField: 'descripcion',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.UnidadMedida',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'datefield',
                                                        fieldLabel: 'Fecha Entrada',
                                                        name: 'fecha_entrada',
                                                        altFormats: '',
                                                        format: 'Y-m-d',
                                                        submitFormat: 'Y-m-d'
                                                    },
                                                    {
                                                        xtype: 'numberfield',
                                                        width: 180,
                                                        fieldLabel: 'Peso Bruto',
                                                        name: 'peso_bruto',
                                                        decimalPrecision: 3,
                                                        decimalSeparator: '.',
                                                        maxValue: 999,
                                                        minValue: 0,
                                                        step: 0.1
                                                    },
                                                    {
                                                        xtype: 'numberfield',
                                                        width: 180,
                                                        fieldLabel: 'Peso Neto',
                                                        name: 'peso_neto',
                                                        decimalPrecision: 3,
                                                        decimalSeparator: '.',
                                                        maxValue: 999,
                                                        minValue: 0,
                                                        step: 0.1
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        fieldLabel: 'Oferta',
                                                        name: 'oferta'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        fieldLabel: 'Activo',
                                                        name: 'activo'
                                                    },
                                                    {
                                                        xtype: 'radiogroup',
                                                        width: 548,
                                                        fieldLabel: 'Producto o Servicio',
                                                        layout: {
                                                            type: 'vbox',
                                                            align: 'stretch'
                                                        },
                                                        items: [
                                                            {
                                                                xtype: 'radiofield',
                                                                flex: 1,
                                                                fieldLabel: 'Producto',
                                                                name: 'producto_servicio',
                                                                value: 1,
                                                                checked: true
                                                            },
                                                            {
                                                                xtype: 'radiofield',
                                                                flex: 1,
                                                                fieldLabel: 'Servicio',
                                                                name: 'producto_servicio',
                                                                value: 2
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                height: 310,
                                                margin: '10 0 0 10',
                                                width: 300,
                                                title: 'Generales',
                                                items: [
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Tipo de Producto',
                                                        name: 'tipo_producto_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.TipoProducto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Categoría',
                                                        name: 'categoria_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.CategoriaProducto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'SubCategoría',
                                                        name: 'subcategoria_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.SubcategoriaProducto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Marca',
                                                        name: 'marca_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.Marca',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Destino',
                                                        name: 'destino_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.DestinoProducto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'combobox',
                                                        fieldLabel: 'Tipo de Costo',
                                                        name: 'tipo_costo_id',
                                                        emptyText: 'Seleccione',
                                                        displayField: 'nombre',
                                                        queryMode: 'local',
                                                        store: 'nomenclador.TipoCosto',
                                                        valueField: 'id'
                                                    },
                                                    {
                                                        xtype: 'textareafield',
                                                        afterLabelTextTpl: [
                                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                                        ],
                                                        fieldLabel: 'Descripción',
                                                        name: 'descripcion',
                                                        allowBlank: false,
                                                        maxLength: 100
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        margin: '10 0 0 0',
                                        title: 'Almacenes',
                                        items: [
                                            {
                                                xtype: 'gridpanel',
                                                store: 'crm.ProductosServiciosAlmacen',
                                                columns: [
                                                    {
                                                        xtype: 'widgetcolumn',
                                                        width: 130,
                                                        dataIndex: 'string',
                                                        text: 'Almacen',
                                                        widget: {
                                                            xtype: 'combobox',
                                                            name: 'almacen_id',
                                                            emptyText: 'Seleccione',
                                                            displayField: 'codigo',
                                                            queryMode: 'local',
                                                            store: 'nomenclador.Almacen',
                                                            valueField: 'id'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'widgetcolumn',
                                                        width: 130,
                                                        dataIndex: 'string',
                                                        text: 'Tipo de Entrada',
                                                        widget: {
                                                            xtype: 'combobox',
                                                            name: 'tipoentrada_id',
                                                            emptyText: 'Seleccione',
                                                            displayField: 'tipoentrada',
                                                            queryMode: 'local',
                                                            store: 'nomenclador.Almacen',
                                                            valueField: 'tipoentrada_id'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'widgetcolumn',
                                                        width: 130,
                                                        dataIndex: 'string',
                                                        text: 'Criterio de Salida',
                                                        widget: {
                                                            xtype: 'combobox',
                                                            name: 'criteriosalida_id',
                                                            emptyText: 'Seleccione',
                                                            displayField: 'criteriosalida',
                                                            queryMode: 'local',
                                                            store: 'nomenclador.Almacen',
                                                            valueField: 'criteriosalida_id'
                                                        }
                                                    },
                                                    {
                                                        xtype: 'widgetcolumn',
                                                        width: 130,
                                                        dataIndex: 'number',
                                                        text: 'Existencia',
                                                        widget: {
                                                            xtype: 'numberfield',
                                                            name: 'existencia',
                                                            decimalPrecision: 3,
                                                            decimalSeparator: '.',
                                                            maxValue: 999,
                                                            minValue: 0,
                                                            step: 0.1
                                                        }
                                                    },
                                                    {
                                                        xtype: 'checkcolumn',
                                                        dataIndex: 'bool',
                                                        text: 'Componentes'
                                                    }
                                                ],
                                                dockedItems: [
                                                    {
                                                        xtype: 'toolbar',
                                                        dock: 'top',
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                itemId: 'mybutton1',
                                                                text: 'Adicionar',
                                                                listeners: {
                                                                    click: 'AdicionarGrid'
                                                                }
                                                            },
                                                            {
                                                                xtype: 'button',
                                                                text: 'Eliminar'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ],
                        dockedItems: [
                            {
                                xtype: 'container',
                                dock: 'bottom',
                                height: 71,
                                padding: 10,
                                layout: 'form',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'saveButton',
                                        margin: 5,
                                        text: 'Guardar',
                                        listeners: {
                                            click: 'saveTreeWindows'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        text: 'Cancelar',
                                        listeners: {
                                            click: 'cancelEdit'
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processFoto: function(config) {
        config.icono = 'address-book';
        return config;
    }

});