/*
 * File: app/view/crm/ProveedorFormViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.crm.ProveedorFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.crmproveedorform',

    saveTreeWindows: function(button, e, eOpts) {
        var form = this.getReferences().form.getForm(),
            record = form.getRecord(),
            store = Ext.StoreManager.lookup('Personas');

        // Valid
        if (form.isValid()) {

            // Update associated record with values
            form.updateRecord();

            // Add to store if new record
            if (record.phantom) {

                // TODO: Assign the record's ID from data source
                // Normally, this value would be auto-generated,
                // or returned from the server
                var id = store.count() + 1;
                record.set('id', id);

                // Add to store
                store.add(record);

            }

            // Commit changes
            store.commitChanges();

            // Display record
            this.select(this, record);

        }
    },

    cancelEdit: function(button, e, eOpts) {
        // Show details
        this.showView('details');
    },

    onFilefieldChange: function(filefield, value, eOpts) {
        console.log(filefield)
        console.log(value)
    },

    onComboboxSelect: function(combo, record, eOpts) {

    },

    onComboboxSelect1: function(combo, record, eOpts) {

    },

    onComboboxSelectEntidad: function(combo, record, eOpts) {

    },

    onTreePanelBeforeItemExpand1: function(nodeinterface, eOpts) {

    }

});
