/*
 * File: app/view/escritorio/Escritorio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.escritorio.Escritorio', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.escritorioescritorio',

    requires: [
        'cerodatax.view.escritorio.EscritorioViewModel',
        'cerodatax.view.escritorio.EscritorioViewController',
        'cerodatax.view.escritorio.Tablero',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Display',
        'Ext.Img',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Separator',
        'cerodatax.view.seguridad.Usuario'
    ],

    controller: 'escritorioescritorio',
    viewModel: {
        type: 'escritorioescritorio'
    },
    itemId: 'viewportEscritorio',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'panelPrincipal',
            margin: '5 0 0 0',
            layout: 'fit',
            listeners: {
                activate: 'onPanelPrincipalActivate'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    border: 2,
                    margin: '5 0 0 0',
                    width: 150,
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'entidadlabel',
                            width: 330,
                            fieldLabel: 'Entidad',
                            labelWidth: 50
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'escritoriotablero'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            margin: '5 0 0 0',
            width: 145,
            layout: 'accordion',
            animCollapse: true,
            collapseDirection: 'left',
            collapsed: false,
            collapsible: true,
            hideCollapseTool: true,
            title: '   Navegación',
            titleCollapse: true,
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'top',
                    height: 90,
                    width: 90,
                    items: [
                        {
                            xtype: 'image',
                            animateShadow: true,
                            frame: true,
                            height: 70,
                            itemId: 'logousuario',
                            margin: '0 0 0 35',
                            width: 70,
                            src: 'resources/images/lunraiz.jpg'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'splitbutton',
                            dock: 'bottom',
                            text: 'Perfil del Usuario',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ayuda'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ayuda en linea'
                                    },
                                    {
                                        xtype: 'menuseparator'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Acerca de'
                                    },
                                    {
                                        xtype: 'menuseparator'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        handler: function(item, e) {
                                            var component =  Ext.create('cerodatax.view.escritorio.FormChangePassword').show();


                                            Ext.ComponentQuery.query('#old_password')[0].focus('', 10);
                                            var logousuario = Ext.ComponentQuery.query('#logousuario')[0];
                                            if(logousuario.username)
                                            Ext.ComponentQuery.query('#username')[0].setValue(logousuario.username);

                                        },
                                        text: 'Cambiar contraseña'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        handler: function(item, e) {
                                            var init = Ext.ComponentQuery.query('#viewportEscritorio')[0];
                                            var myMask = new Ext.LoadMask({
                                                msg    : 'Cerrando Sessión...',
                                                target : init
                                            });
                                            myMask.show();
                                            var successCallback = function(resp, ops) {
                                                //debugger;

                                                var json = Ext.JSON.decode(resp.responseText);



                                                if(json.success===true) // cambiar cuando se creen usuario bien
                                                {
                                                    window.location = 'index.php?auth/login';
                                                    window.location ='';
                                                }
                                                else{
                                                    myMask.unmask();
                                                    var s='El usuario no pudo cerrar sessión.';
                                                    var title='Error';
                                                    var icon = 'xf057@FontAwesome';

                                                    Ext.toast({
                                                        html: s ,
                                                        glyph:icon,
                                                        closable: false,
                                                        align: 't',
                                                        title:title,
                                                        slideInDuration: 400,
                                                        minWidth: 400
                                                    });
                                                }

                                            };




                                            // Failure
                                            var failureCallback = function(resp, ops) {

                                                myMask.unmask();
                                                var s='El usuario no pudo cerrar sessión.';
                                                var title='Error';
                                                var icon = 'xf057@FontAwesome';

                                                Ext.toast({
                                                    html: s ,
                                                    glyph:icon,
                                                    closable: false,
                                                    align: 't',
                                                    title:title,
                                                    slideInDuration: 400,
                                                    minWidth: 400
                                                });


                                            };
                                            Ext.Ajax.request({
                                                url: 'index.php/auth/logout',
                                                method: 'POST',
                                                success: successCallback,
                                                failure: failureCallback

                                            });
                                        },
                                        text: 'Cerrar sesión'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]

});