/*
 * File: app/view/escritorio/Escritorio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.escritorio.Escritorio', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.escritorioescritorio',

    requires: [
        'cerodatax.view.escritorio.EscritorioViewModel',
        'cerodatax.view.seguridad.Usuario',
        'cerodatax.view.seguridad.Rol',
        'cerodatax.view.seguridad.Accion',
        'cerodatax.view.estructura.Entidad',
        'cerodatax.view.estructura.Area',
        'cerodatax.view.persona.Persona',
        'cerodatax.view.persona.Cargo',
        'cerodatax.view.actualizacion.Actualizacion',
        'cerodatax.view.nomenclador.Sexo',
        'cerodatax.view.nomenclador.Defensa',
        'cerodatax.view.nomenclador.EstadoCivil',
        'cerodatax.view.nomenclador.ColorPiel',
        'cerodatax.view.nomenclador.GrupoSanguineo',
        'cerodatax.view.nomenclador.TipoEntidad',
        'cerodatax.view.nomenclador.TipoRegistro',
        'cerodatax.view.nomenclador.NAE',
        'cerodatax.view.nomenclador.Union',
        'cerodatax.view.nomenclador.Moneda',
        'cerodatax.view.nomenclador.SeccionNAE',
        'cerodatax.view.nomenclador.DivisionNAE',
        'cerodatax.view.nomenclador.Categoria',
        'cerodatax.view.nomenclador.CategoriaEntidad',
        'cerodatax.view.nomenclador.Clasificacion',
        'cerodatax.view.nomenclador.Organismo',
        'cerodatax.view.nomenclador.Pais',
        'cerodatax.view.nomenclador.Continente',
        'cerodatax.view.nomenclador.Provincia',
        'cerodatax.view.nomenclador.Municipio',
        'cerodatax.view.nomenclador.NivelEducacional',
        'cerodatax.view.nomenclador.Calificador',
        'cerodatax.view.nomenclador.GrupoEscala',
        'Ext.Img',
        'Ext.form.FieldSet',
        'Ext.button.Segmented',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'escritorioescritorio'
    },
    itemId: 'viewportEscritorio',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            collapseMode: 'mini',
            region: 'north',
            height: 150,
            itemId: 'headerPanel',
            animCollapse: false,
            collapseDirection: 'top',
            collapsed: true,
            collapsible: true,
            title: '',
            dockedItems: [
                {
                    xtype: 'image',
                    dock: 'left',
                    height: 80,
                    width: 185,
                    src: 'resources/images/logoASEGURA.png',
                    title: 'Logo'
                },
                {
                    xtype: 'fieldset',
                    dock: 'right',
                    width: 130,
                    title: 'Perfil del Usuario',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'image',
                            height: 100,
                            width: 100,
                            src: 'resources/images/avatarHombre.png',
                            title: 'Usuario'
                        },
                        {
                            xtype: 'segmentedbutton',
                            items: [
                                {
                                    itemId: 'btnEdit',
                                    text: 'Editar'
                                },
                                {
                                    text: 'Cerrar'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'menuPanel',
            width: 180,
            collapseDirection: 'left',
            collapsed: false,
            collapsible: true,
            title: 'Operaciones',
            layout: {
                type: 'accordion',
                hideCollapseTool: true
            },
            items: [
                {
                    xtype: 'panel',
                    width: 165,
                    layout: 'accordion',
                    animCollapse: true,
                    collapsed: true,
                    collapsible: false,
                    title: 'Administración',
                    titleCollapse: false,
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menuAdministracion',
                            collapsed: true,
                            title: 'Generales',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuSeguridad',
                                    text: 'Seguridad',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuEstructuras',
                                    text: 'Estructuras',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuPersonas',
                                    text: 'Personas',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuActualizaciones',
                                    text: 'Actualizaciónes',
                                    focusable: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    width: 144,
                    layout: 'accordion',
                    animCollapse: false,
                    collapseFirst: false,
                    collapsed: true,
                    collapsible: false,
                    title: 'Nomencladores',
                    titleCollapse: false,
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            hidden: false,
                            itemId: 'menuGenerales',
                            animCollapse: true,
                            collapsed: true,
                            title: 'Generales',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuMunicipios',
                                    text: 'Municipios',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuProvincias',
                                    text: 'Provincias',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuPaises',
                                    text: 'Países',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuContinentes',
                                    text: 'Continentes',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuMoneda',
                                    text: 'Monedas',
                                    focusable: true
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            floating: false,
                            hidden: false,
                            itemId: 'menuEntidad',
                            animCollapse: true,
                            title: 'Entidades',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuOrganismos',
                                    text: 'Organismos',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuClasificaciones',
                                    text: 'Clasificaciónes',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuTipoRegistro',
                                    text: 'Tipos Registro',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuCategoriasEntidades',
                                    text: 'Categorías',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuSeccionNAE',
                                    text: 'Seccion NAE',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuDivisionNAE',
                                    text: 'Division NAE',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuNAE',
                                    text: 'NAE',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuTipos',
                                    text: 'Tipos',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuUnion',
                                    text: 'Unión',
                                    focusable: true
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            floating: false,
                            hidden: false,
                            itemId: 'menuPersona',
                            animCollapse: true,
                            frameHeader: false,
                            title: 'Personas',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuNivelesEducacionales',
                                    text: 'Niveles Educacionales',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuGruposSanguineos',
                                    text: 'Grupos Sanguíneos',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuColoresPiel',
                                    text: 'Colores de Piel',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuEstadosCiviles',
                                    text: 'Estados Civil',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuDefensas',
                                    text: 'Defensas',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuSexos',
                                    text: 'Sexos',
                                    focusable: true
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            floating: false,
                            hidden: false,
                            itemId: 'menuCargos',
                            animCollapse: true,
                            title: 'Cargos',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuGruposEscalas',
                                    text: 'Grupos Escalas',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuCalificadores',
                                    text: 'Calificadores',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'menuCategorias',
                                    text: 'Categorías',
                                    focusable: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    animCollapse: true,
                    collapseFirst: false,
                    title: 'Configuraciónes',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menuConfiguraciones',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item',
                                    focusable: true
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Menu Item',
                                    focusable: true
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            itemId: 'panelPrincipal',
            layout: 'fit',
            items: [
                {
                    xtype: 'tabpanel',
                    hidden: true,
                    itemId: 'panelSeguridad',
                    animCollapse: true,
                    closeAction: 'hide',
                    collapseFirst: false,
                    title: 'Seguridad',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'seguridadusuario',
                            itemId: 'panelUsuarios',
                            title: 'Usuarios'
                        },
                        {
                            xtype: 'seguridadrol',
                            itemId: 'panelRoles',
                            title: 'Roles'
                        },
                        {
                            xtype: 'seguridadaccion',
                            itemId: 'panelAcciones',
                            title: 'Acciones'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    hidden: true,
                    itemId: 'panelEstructuras',
                    animCollapse: true,
                    collapseFirst: false,
                    title: 'Estructura',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'estructuraentidad',
                            itemId: 'panelEntidades',
                            width: '80%',
                            title: 'Entidades'
                        },
                        {
                            xtype: 'estructuraarea',
                            itemId: 'panelAreas',
                            title: 'Áreas'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    itemId: 'panelPersonas',
                    animCollapse: true,
                    collapseFirst: false,
                    title: 'Personas',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'personapersona',
                            itemId: 'panelPersonas',
                            title: 'Personas'
                        },
                        {
                            xtype: 'personacargo',
                            itemId: 'panelCargos',
                            title: 'Cargos'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    hidden: true,
                    itemId: 'panelActualizaciones',
                    animCollapse: true,
                    collapseFirst: false,
                    title: 'Actualizaciones',
                    items: [
                        {
                            xtype: 'actualizacionactualizacion',
                            itemId: 'panelSistema',
                            title: 'Sistema'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    border: false,
                    hidden: true,
                    itemId: 'panelSexos',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorsexo',
                            border: false,
                            itemId: 'panelSexos',
                            title: 'Sexos'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelDefensas',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladordefensa',
                            itemId: 'panelDefensas',
                            title: 'Defensas'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelEstadosCiviles',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorestadocivil',
                            itemId: 'panelEstadosCiviles',
                            title: 'Estados Civiles'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelColoresPiel',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorcolorpiel',
                            itemId: 'panelColoresPiel',
                            title: 'Colores de Piel'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelGruposSanguineos',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorgruposanguineo',
                            itemId: 'panelGruposSanguineos',
                            title: 'Grupos Sanguineos'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelTipos',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladortipoentidad',
                            itemId: 'panelTipos',
                            title: 'Tipos de Entidades'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelTipoRegistro',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladortiporegistro',
                            itemId: 'panelTipoRegistro',
                            title: 'Tipos de Registro'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelNAE',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladornae',
                            itemId: 'panelNAE',
                            title: 'NAE'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelUnion',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorunion',
                            itemId: 'panelUnion',
                            title: 'Unión'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelMoneda',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladormoneda',
                            itemId: 'panelMoneda',
                            title: 'Moneda'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelSeccionNAE',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorseccionnae',
                            itemId: 'panelSeccionNAE',
                            title: 'Sección NAE'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelDivisionNAE',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladordivisionnae',
                            itemId: 'panelDivisionNAE',
                            title: 'Division NAE'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelCategorias',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorcategoria',
                            title: 'Categorias de Cargos'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelCategoriasEntidades',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorcategoriaentidad',
                            title: 'Categorias de Entidad'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelClasificaciones',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorclasificacion',
                            title: 'Clasificaciones'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelOrganismos',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladororganismo',
                            itemId: 'panelOrganismos',
                            title: 'Organismos'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelPaises',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorpais',
                            itemId: 'panelPaises',
                            title: 'Paises'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelContinentes',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorcontinente',
                            itemId: 'panelContinentes',
                            title: 'Continentes'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelProvincias',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorprovincia',
                            itemId: 'panelProvincias',
                            title: 'Provincias'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelMunicipios',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladormunicipio',
                            itemId: 'panelMunicipios',
                            title: 'Municipios'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelNivelesEducacionales',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorniveleducacional',
                            itemId: 'panelNivelesEducacionales',
                            title: 'Niveles Educacionales'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelCalificadores',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorcalificador',
                            itemId: 'panelCalificadores',
                            title: 'Calificadores'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    hidden: true,
                    itemId: 'panelGruposEscalas',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'nomencladorgrupoescala',
                            itemId: 'panelGruposEscalas',
                            title: 'Grupos Escalas'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    hidden: true,
                    itemId: 'panelTableros',
                    animCollapse: true,
                    collapseFirst: false,
                    title: 'Tableros de control',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 340,
                            title: 'Sistema'
                        },
                        {
                            xtype: 'panel',
                            height: 340,
                            title: 'Administración'
                        }
                    ]
                }
            ]
        }
    ]

});