/*
 * File: app/view/escritorio/FormChangePassword.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.escritorio.FormChangePassword', {
    extend: 'Ext.window.Window',
    alias: 'widget.escritorioformchangepassword',

    requires: [
        'cerodatax.view.escritorio.FormAutenticacionViewModel1',
        'cerodatax.view.escritorio.FormAutenticacionViewController1',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Display',
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.button.Button',
        'cerodatax.view.escritorio.Escritorio'
    ],

    controller: 'escritorioformchangepassword',
    viewModel: {
        type: 'escritorioformchangepassword'
    },
    animateShadow: true,
    frame: true,
    id: 'windowsAutenticacion1',
    itemId: 'windowsAutenticacion',
    width: 340,
    layout: 'fit',
    bodyPadding: 10,
    title: 'Cambiar contraseña',
    modal: true,

    items: [
        {
            xtype: 'form',
            fieldDefaults: {
                maxLength: 30,
                enforceMaxLength: true
            },
            items: [
                {
                    xtype: 'container',
                    height: 120,
                    width: 130,
                    items: [
                        {
                            xtype: 'image',
                            alwaysOnTop: true,
                            shim: false,
                            frame: true,
                            height: 100,
                            itemId: 'foto1',
                            style: 'font-size: 110px; margin: 10px;line-height: 120px;',
                            width: 100,
                            alt: 'Cargando Contraseña...',
                            glyph: 'xf084@FontAwesome'
                        }
                    ]
                },
                {
                    xtype: 'displayfield',
                    itemId: 'username',
                    fieldLabel: 'Usuario',
                    labelWidth: 140,
                    name: 'username'
                },
                {
                    xtype: 'textfield',
                    id: 'old_password',
                    itemId: 'old_password',
                    afterLabelTextTpl: [
                        '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                    ],
                    fieldLabel: 'Contraseña anterior',
                    labelWidth: 140,
                    name: 'old_password',
                    inputType: 'password',
                    allowBlank: false,
                    regex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,100}$/,
                    regexText: 'La contraseña debe tener más de 6 caracteres, al menos un caracter numérico y una letra mayúscula.'
                },
                {
                    xtype: 'textfield',
                    id: 'new_password',
                    itemId: 'new_password',
                    afterLabelTextTpl: [
                        '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                    ],
                    fieldLabel: 'Nueva contraseña',
                    labelWidth: 140,
                    name: 'new_password',
                    inputType: 'password',
                    allowBlank: false,
                    regex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,100}$/,
                    regexText: 'La contraseña debe tener más de 6 caracteres, al menos un caracter numérico y una letra mayúscula.'
                },
                {
                    xtype: 'textfield',
                    validator: function(value) {
                        var pass1 = Ext.getCmp('new_password').getValue();
                        if (String(pass1) != String(value) && String(value) !== "")
                        return "Las contraseñas no coinciden.";
                        else
                        return true;
                    },
                    itemId: 'confirmacion_password',
                    afterLabelTextTpl: [
                        '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                    ],
                    fieldLabel: 'Confirmar contraseña',
                    labelWidth: 140,
                    name: 'confirmacion_password',
                    inputType: 'password',
                    allowBlank: false,
                    regex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,100}$/,
                    regexText: 'La contraseña debe tener más de 6 caracteres, al menos un caracter numérico y una letra mayúscula.'
                },
                {
                    xtype: 'button',
                    formBind: true,
                    animateShadow: true,
                    id: 'buttonChangePassword',
                    itemId: 'buttonChangePassword',
                    width: 315,
                    text: 'Enviar'
                }
            ],
            listeners: {
                afterrender: 'onWindowsChangePasswordAfterRender'
            }
        }
    ]

});