/*
 * File: app/view/escritorio/FormAutenticacion.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.escritorio.FormAutenticacion', {
    extend: 'Ext.form.Panel',
    alias: 'widget.escritorioformautenticacion',

    requires: [
        'cerodatax.view.escritorio.FormAutenticacionViewModel',
        'Ext.Img',
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'cerodatax.view.escritorio.Escritorio'
    ],

    viewModel: {
        type: 'escritorioformautenticacion'
    },
    animateShadow: true,
    alignTarget: 'center',
    autoShow: true,
    frame: true,
    itemId: 'windowsAutenticacion',
    width: 320,
    bodyPadding: 10,
    title: 'Autenticación',
    fieldDefaults: {
        defaultType: 'textfield',
        anchor: '100%',
        labelWidth: 120
    },

    dockedItems: [
        {
            xtype: 'image',
            dock: 'top',
            height: 318,
            width: 318,
            src: 'resources/images/lunraiz.jpg'
        }
    ],
    items: [
        {
            xtype: 'textfield',
            fieldLabel: 'Usuario',
            emptyText: 'usuario',
            selectOnFocus: true
        },
        {
            xtype: 'textfield',
            fieldLabel: 'Contraseña',
            inputType: 'password',
            emptyText: 'contraseña'
        },
        {
            xtype: 'checkboxfield',
            hidden: true,
            fieldLabel: 'Recordarme',
            name: 'recordarme'
        },
        {
            xtype: 'button',
            itemId: 'buttonAutenticacion',
            text: 'Iniciar Session'
        }
    ]

});