/*
 * File: app/view/nomenclador/contabilidad/CuentaContableForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.nomenclador.contabilidad.CuentaContableForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.cuentacontableForm',

    requires: [
        'cerodatax.view.nomenclador.AlmacenFormViewModel3',
        'cerodatax.view.nomenclador.AlmacenFormViewController3',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.XTemplate',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'nomencladorcontabilidadcuentacontableform',
    viewModel: {
        type: 'nomencladorcontabilidadcuentacontableform'
    },
    controller: 'nomencladorcrud',
    height: 500,
    resizable: false,
    width: 645,
    bodyPadding: 10,
    title: 'Cuenta Contable',
    modal: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    me.processForm({
                        xtype: 'form',
                        reference: 'form',
                        height: 474,
                        width: 625,
                        bodyPadding: 10,
                        fieldDefaults: {
                            maxLength: 100,
                            enforceMaxLength: true
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                alignTarget: 'top',
                                height: 194,
                                width: 601,
                                layout: 'column',
                                title: 'Información',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Cuenta',
                                        name: 'nombre',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        margin: '0 0 0 10',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'SubCuenta',
                                        labelWidth: 110,
                                        name: 'subcuenta',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        margin: '10 0 0 0',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Análisis',
                                        name: 'analisis',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        margin: '10 0 0 10',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'SubAnálisis',
                                        labelWidth: 110,
                                        name: 'subanalisis',
                                        allowBlank: false,
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        margin: '10 0 0 0',
                                        fieldLabel: 'Epígrafe',
                                        name: 'epigrafe',
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'textfield',
                                        margin: '10 0 0 10',
                                        fieldLabel: 'Partida',
                                        labelWidth: 110,
                                        name: 'partida',
                                        maxLength: 100
                                    },
                                    {
                                        xtype: 'radiogroup',
                                        margin: '10 0 0 0',
                                        width: 275,
                                        fieldLabel: 'Naturaleza',
                                        layout: {
                                            type: 'vbox',
                                            align: 'stretch'
                                        },
                                        items: [
                                            {
                                                xtype: 'radiofield',
                                                flex: 1,
                                                name: 'naturaleza',
                                                value: 1,
                                                boxLabel: 'Débito',
                                                checked: true
                                            },
                                            {
                                                xtype: 'radiofield',
                                                name: 'naturaleza',
                                                value: 2,
                                                boxLabel: 'Credito'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'combobox',
                                        margin: '10 0 0 10',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Tipo de Cuenta',
                                        labelWidth: 110,
                                        name: 'tipocuenta_id',
                                        allowBlank: false,
                                        emptyText: 'Seleccione',
                                        displayField: 'nombre',
                                        queryMode: 'local',
                                        queryParam: 'clasificaciontipocuenta_id:false',
                                        store: 'nomenclador.contabilidad.TipoCuenta',
                                        valueField: 'id',
                                        listeners: {
                                            select: 'onComboboxSelect'
                                        }
                                    },
                                    {
                                        xtype: 'combobox',
                                        disabled: true,
                                        margin: '10 0 0 10',
                                        afterLabelTextTpl: [
                                            '<span style="color:#D94E37; font-weight:bold" data-qtip="Requerido"> * </span>'
                                        ],
                                        fieldLabel: 'Clasificación TC',
                                        labelWidth: 110,
                                        name: 'clasificaciontipocuenta_id',
                                        allowBlank: false,
                                        emptyText: 'Seleccione',
                                        displayField: 'nombre',
                                        queryMode: 'local',
                                        store: 'nomenclador.contabilidad.ClasificacionTipoCuenta',
                                        valueField: 'id'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 188,
                                width: 670,
                                layout: 'column',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        height: 175,
                                        width: 302,
                                        layout: 'form',
                                        title: 'Generales',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                fieldLabel: 'Se Análisis Elemento y/o Subelemento',
                                                name: 'analisis_elemento_subelemento',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                margin: '0 0 0 10',
                                                width: 150,
                                                fieldLabel: 'Cuenta Banco',
                                                name: 'cuenta_banco',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                margin: '0 0 0 10',
                                                width: 150,
                                                fieldLabel: 'Ultimo Nivel de Anotación',
                                                name: 'ultimo_nivel_anotacion',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                fieldLabel: 'Descontuinada',
                                                name: 'descontuinada',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                margin: '0 0 0 10',
                                                fieldLabel: 'Enviar No Resumida',
                                                name: 'enviar_no_resumida',
                                                checked: true
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        height: 175,
                                        margin: '0 0 0 10',
                                        width: 290,
                                        layout: 'form',
                                        title: 'Generales',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                fieldLabel: 'Incluir a Gastos',
                                                name: 'incluir_a_gastos',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                margin: '0 0 0 10',
                                                width: 150,
                                                fieldLabel: 'Reguladora',
                                                name: 'reguladora',
                                                checked: true
                                            },
                                            {
                                                xtype: 'checkboxfield',
                                                margin: '0 0 0 10',
                                                width: 150,
                                                fieldLabel: 'Cuenta de M.Base',
                                                name: 'cuenta_base',
                                                checked: true
                                            }
                                        ]
                                    }
                                ]
                            }
                        ],
                        dockedItems: [
                            {
                                xtype: 'container',
                                dock: 'bottom',
                                height: 84,
                                padding: 10,
                                layout: 'form',
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'saveButton',
                                        margin: 5,
                                        text: 'Guardar',
                                        listeners: {
                                            click: 'saveTreeWindows'
                                        }
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'cancelButton',
                                        margin: 5,
                                        text: 'Cancelar',
                                        listeners: {
                                            click: 'cancelEdit'
                                        }
                                    }
                                ]
                            }
                        ]
                    })
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processForm: function(config) {
        return config;
    }

});