/*
 * File: app/view/seguridad/UsuarioRolForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('cerodatax.view.seguridad.UsuarioRolForm', {
    extend: 'Ext.window.Window',
    alias: 'widget.usuariorolForm',

    requires: [
        'cerodatax.view.seguridad.UsuarioRolFormViewModel',
        'cerodatax.view.seguridad.UsuarioRolFormViewController',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.view.MultiSelector',
        'Ext.view.MultiSelectorSearch',
        'Ext.view.Table',
        'Ext.button.Button'
    ],

    controller: 'seguridadusuariorolform',
    viewModel: {
        type: 'seguridadusuariorolform'
    },
    controller: 'nomencladorcrud',
    resizable: false,
    bodyPadding: 10,
    title: 'Roles',
    modal: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            height: 480,
            width: 400,
            layout: 'auto',
            bodyPadding: 10,
            fieldDefaults: {
                padding: '0 10 0 0',
                enforceMaxLength: true
            },
            items: [
                {
                    xtype: 'displayfield',
                    width: 380,
                    fieldLabel: 'Usuario',
                    name: 'identity'
                },
                {
                    xtype: 'multiselector',
                    title: 'Roles',
                    store: 'seguridad.Rol',
                    search: {
                        xtype: 'multiselector-search',
                        store: 'seguridad.Rol'
                    },
                    viewConfig: {
                        deferEmptyText: false
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    padding: 10,
                    layout: 'form',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'saveButton',
                            margin: 5,
                            text: 'Guardar',
                            listeners: {
                                click: 'saveTreeWindows'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'cancelButton',
                            margin: 5,
                            text: 'Cancelar',
                            listeners: {
                                click: 'cancelEdit'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});